list: $/niainteractive/event/models/event/columns.yaml
modelClass: NiaInteractive\Event\Models\Event
title: Events
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'niainteractive/event/events/update/:id'
